# constants.py

TRANSACTIONS_TABLE_NAME = "transactions"
ACCOUNTS_TABLE_NAME = "accounts"

DEPOSIT_COMMAND = "DEPOSIT"
WITHDRAW_COMMAND = "WITHDRAW"
XFER_COMMAND = "XFER"
FREEZE_COMMAND = "FREEZE"
THAW_COMMAND = "THAW"

ACCOUNT_ID_FIELD = "accountId"
FROM_ID_FIELD = "fromId"
TO_ID_FIELD = "toId"
AMOUNT_FIELD = "amount"
